### PR TITLE
Universal Objects are Isomorphic

### PR DESCRIPTION
**Pull request by Jake-Gillberg**
Wondering if the proof should be done this way, or start with `InitialObjectsAreIsomorphic` and use properties of Dual Categories to complete

### CODE REVIEW

**Comment by marcosh** [comment]
hi @Jake-Gillberg thanks for your contribution.

I guess it would be nice to use `initialObjectsAreIsomorphic` to prove `Isomorphic (dualCategory cat) (carrier a) (carrier b)` and then, adding some code in `DualCategory.lidr`, prove that two objects are isomorphic in a category only if they are isomorphic in the dual category.

What do you say?

**Comment by Jake-Gillberg** [comment]
I'll give it a go!

**Comment by Jake-Gillberg** [comment]
Closing while work in progress

**Comment by Jake-Gillberg** [comment]
@marcosh this should be good to go!

**Comment by marcosh** [comment]
thanks @Jake-Gillberg, this looks awesome! I merged it manually

**Pull request closed without merging**
