### PR TITLE
Cocones and colimits

### PR DESCRIPTION
**Pull request by mstn**
Cocones and colimits as promised.

What is still missing

- [x] ~~Fix https://github.com/statebox/idris-ct/compare/master...mstn:cocone-category?expand=1#diff-a430d98f9e16ada8232398b022692081R45. If I replace `(\e => absurd e)` with `nil`, I get this error https://github.com/idris-lang/Idris-dev/issues/3133~~ (not relevant anymore)
- [ ] Prove that CoProduct is a CoLimit
- [ ] Improve proofs readability

### CODE REVIEW

**Comment by marcosh** [comment]
hi there, thanks for this!

I'd like to propose you to follow a slightly different approach to approach these definitions:

- define a diagram simply as a functor from an indexing category J to C (https://en.wikipedia.org/wiki/Diagram_(category_theory))
- define a co-cone for a diagram F as a natural transformation from F to Δ(N), where N is the apex of the co-cone (https://en.wikipedia.org/wiki/Cone_(category_theory)#Equivalent_formulations)

**Comment by mstn** [comment]
@marcosh I followed your advice for diagrams. I proved that cocones are natural isomorphisms, but I did not define a cocone as a nat isom directly. I think that we need to define the functor category, first.

ps: I will clean the code a bit tomorrow

**Comment by marcosh** [comment]
@mstn I tried to experiment a bit and it looks like we could use natural transformations to define cocones without any particular problem (or maybe you have in mind something I didn't check). 

You can take a look at https://github.com/statebox/idris-ct/tree/cocone-category-marcosh

**Comment by marcosh** [comment]
@mstn great work as usual!

I did my usual minor edits and now it is ready to be merged.

Before doing it, I would like to ask you to sign our Contributor License Agreement. It is just some legal stuff we set up to make sure we, being a commercial company, have the right to use this open source software freely. It should be enough to click on Details near the clahub CI step and fill the short form.
Please ask if you need some more clarifications

**Pull request merged**
