### PR TITLE
Slice categories (over- and undercategories)

### PR DESCRIPTION
**Pull request by jcranch**
Here's some actual code. Some of the names may want changing.

### CODE REVIEW

**Comment by marcosh** [comment]
hi @jcranch that looks awesome!

What would you say about implementing directly [comma categories](https://en.wikipedia.org/wiki/Comma_category) and then having slice and coslice categories as special cases?

**Comment by jcranch** [comment]
Ha, I was partly thinking of it as a bit of a warmup exercise before doing commas. :-)

Philosophically, I don't know to what extent you wish to have separate specialisations of various concepts. There could be savings of ease and efficiency keeping under/overs separate from commas, the same way as (for example) you've got products as a separate specialisation of limits.

**Comment by marcosh** [comment]
In this case I feel it would be nicer to have slice and coslice categories defined in terms of comma categories.

I hope it'll be rather easy to define them once you have comma categories, which definition shouldn't be too much harder than what you already did

**Comment by jcranch** [comment]
If you like.

But that will require a few other bits of infrastructure. I can't see that anyone's implemented the terminal category, and the isomorphism between functors 1->C and objects of C yet. That would be desirable.

**Comment by marcosh** [comment]
for the terminal category, we could use [`discreteCategory ()`](https://github.com/statebox/idris-ct/blob/1f63343d9779916c9c4fa7d7a062d71cedf83e39/src/Discrete/DiscreteCategory.lidr#L52)

If you need some prerequisites, you could leave some holes and then I could fill them, or we could work together on them

**Comment by jcranch** [comment]
One could indeed define
  `terminalCategory = discreteCategory ()`,
but there's a certain cost in doing so. This is a one-object category where the hom type between the object and itself is () = (). That's a one-object type, but it's a very slightly harder one-object type to work with than (). If I were you, I'd define a specialised terminal category, with type of objects () and hom type (), and prove it isomorphic to discreteCategory ().

For comparison, I notice someone has gone to the trouble of defining a specialised emptyCategory, when one could similarly define
  `emptyCategory = discreteCategory Void`.
I'm not sure I disagree with that decision, but I think a specialised terminal category is significantly more worthwhile than a specialised initial category, since pretty much all properties of the initial category follow immediately from the property that its type of objects is initial, whereas there are many categories whose object type is terminal.

**Pull request closed without merging**
